[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[language.config]
config.cargo.features = "all"

[[language]]
name = "cpp"
language-server = { command = "clangd", args=["--compile-commands-dir=compile_commands_directory"] }

[[language]]
name = "c"
language-server = { command = "clangd", args=["--compile-commands-dir=compile_commands_directory"]  }
